name: YoutubePL
author: Moogkiki
category: Media
tags: [widgets, youtube, google api, interface]
#docs: http://moog.moonkiki.com/2010/03/28/a-youtube-playlist/
#demo: http://moog.moonkiki.com/MooG/plugin/YoutubePL/youtubePLDemo.html
#current: 0.1